import rosinstall
from wstool import config
import os
import argparse
import urlparse

parser = argparse.ArgumentParser()
parser.add_argument('parent_rosinstall', type=str)
parser.add_argument('current_rosinstall', type=str)
parser.add_argument('outfilename', type=str, default='.rosinstall.gen')
args = parser.parse_args()

parent_rosinstall_uri = urlparse.urljoin('file://', os.path.abspath(args.parent_rosinstall))
current_rosinstall_uri = urlparse.urljoin('file://', os.path.abspath(args.current_rosinstall))
install_path = os.path.dirname(os.path.abspath(args.current_rosinstall))
filename = args.outfilename

# install_path = '/root/ros_catkin_ws/common_pkgs_deps'
# filename = '.rosinstall.diffgen'
# parent_rosinstall_uri = 'file:///root/ros_catkin_ws/parent/melodic-desktop-full.rosinstall'
# current_rosinstall_uri = 'file:///root/ros_catkin_ws/common_pkgs_deps/.rosinstall'

parentspecs = rosinstall.wstool.config_yaml.get_path_specs_from_uri(parent_rosinstall_uri)
currentspecs = rosinstall.wstool.config_yaml.get_path_specs_from_uri(current_rosinstall_uri)
pickup_names = set(spec.get_local_name() for spec in currentspecs) - set(spec.get_local_name() for spec in parentspecs)
d = {spec.get_local_name() : spec for spec in currentspecs}
pickup_specs = []
for n in pickup_names:
    pickup_specs.append(d[n])


cfg = config.Config(pickup_specs, install_path)
rosinstall.wstool.config_yaml.generate_config_yaml(cfg, filename, header="# This file is automatically generated\n")


